################################################################################
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
        component: cluster
    spec:
      containers:
      - name: jobmanager
        image: flink-dev
        imagePullPolicy: IfNotPresent
        args:
        - "cluster"
        - "-i"
        - "flink-dev"
        - "-cid"
        - "test"
        env:
        - name: EXTRA_CLASSPATHS
          value: /flink-root/flink-kubernetes/target/classes
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 6125
          name: query
        - containerPort: 8081
          name: ui
        volumeMounts:
          - mountPath: /opt/flink
            name: flink-dist
          - mountPath: /flink-root
            name: flink-root
      volumes:
          - name: flink-dist
            hostPath:
                path: /flink-root/build-target
          - name: flink-root
            hostPath:
              path: /flink-root
---

apiVersion: v1
kind: Service
metadata:
  name: flink-cluster
spec:
  ports:
  - name: rpc
    port: 6123
  - name: blob
    port: 6124
  - name: query
    port: 6125
  - name: ui
    port: 8081
  selector:
    app: flink
    component: cluster
  externalIPs:
   - 192.168.99.100

